/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Clean old caches
cleanupOutdatedCaches();

// Precache resources generated by build
precacheAndRoute(self.__WB_MANIFEST);

// Runtime Caching for Supabase Storage/API
registerRoute(
    ({ url }) => url.href.match(/^https:\/\/.*supabase\.co\/.*/i),
    new NetworkFirst({
        cacheName: 'supabase-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 24 * 60 * 60, // 24 Hours
            }),
        ],
    })
);

// --- PUSH NOTIFICATION LISTENERS ---

type PushData = { title: string; body: string; icon: string; url: string; tag?: string; tel?: string; nome?: string; leadId?: string };

const isMobileDevice = () => /Android|iPhone|iPad|iPod|Mobile/i.test(self.navigator.userAgent || '');

// Página do Inmovya que abre o discador do celular para o telefone do lead
const callUrl = (data: Partial<PushData>) => {
    const params = new URLSearchParams();
    if (data.tel) params.set('ligar', data.tel);
    if (data.leadId) params.set('leadId', data.leadId);
    if (data.nome) params.set('nome', data.nome);
    return '/?' + params.toString();
};

self.addEventListener('push', (event) => {
    let data: PushData = { title: 'Inmovya', body: 'Nova notificação', icon: '/icons/icon-192x192.png', url: '/' };

    if (event.data) {
        try {
            const json = event.data.json();
            data = { ...data, ...json };
        } catch (e) {
            data.body = event.data.text();
        }
    }

    const options: any = {
        body: data.body,
        icon: data.icon,
        badge: data.icon, // Android small icon usually needs to be white/transparent, but using main icon as fallback
        vibrate: data.tel ? [300, 100, 300, 100, 300] : [100, 50, 100],
        tag: data.tag,
        requireInteraction: !!data.tag,
        data: { url: data.url, tel: data.tel, nome: data.nome, leadId: data.leadId }
    };
    if (data.tel) {
        options.actions = [
            { action: 'ligar', title: '📞 Ligar agora' },
            { action: 'abrir', title: 'Abrir lead' }
        ];
    }

    event.waitUntil(self.registration.showNotification(data.title, options as NotificationOptions));
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const data = (event.notification.data || {}) as Partial<PushData>;

    // Lead novo com telefone: no celular, tocar na notificação (ou em "Ligar agora") já liga
    const wantsCall = !!data.tel && (event.action === 'ligar' || (event.action !== 'abrir' && isMobileDevice()));
    const targetUrl = wantsCall ? callUrl(data) : (data.url || '/');

    event.waitUntil((async () => {
        if (wantsCall && self.clients.openWindow) {
            // Janela nova ganha o "toque" do usuário, o que permite abrir o discador na hora
            return self.clients.openWindow(targetUrl);
        }
        const clientList = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
        for (const client of clientList) {
            if ('focus' in client) {
                await (client as WindowClient).focus();
                return (client as WindowClient).navigate(targetUrl);
            }
        }
        if (self.clients.openWindow) return self.clients.openWindow(targetUrl);
    })());
});
