/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Clean old caches
cleanupOutdatedCaches();

// Precache resources generated by build
precacheAndRoute(self.__WB_MANIFEST);

// Runtime Caching for Supabase Storage/API
registerRoute(
    ({ url }) => url.href.match(/^https:\/\/.*supabase\.co\/.*/i),
    new NetworkFirst({
        cacheName: 'supabase-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 24 * 60 * 60, // 24 Hours
            }),
        ],
    })
);

// --- PUSH NOTIFICATION LISTENERS ---

self.addEventListener('push', (event) => {
    let data = { title: 'Inmovya', body: 'Nova notificação', icon: '/icons/icon-192x192.png', url: '/' };

    if (event.data) {
        try {
            const json = event.data.json();
            data = { ...data, ...json };
        } catch (e) {
            data.body = event.data.text();
        }
    }

    event.waitUntil(
        self.registration.showNotification(data.title, {
            body: data.body,
            icon: data.icon,
            badge: data.icon, // Android small icon usually needs to be white/transparent, but using main icon as fallback
            vibrate: [100, 50, 100],
            data: { url: data.url }
        })
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            // If there is a window open, focus it
            for (const client of clientList) {
                if (client.url && 'focus' in client) {
                    return client.focus();
                }
            }
            // If no window open, open a new one
            if (self.clients.openWindow && event.notification.data.url) {
                return self.clients.openWindow(event.notification.data.url);
            }
        })
    );
});
